"""latest update

Revision ID: 36db15afab00
Revises: 9f8dc147193d
Create Date: 2024-10-17 11:35:04.892178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36db15afab00'
down_revision = '9f8dc147193d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password_hash', sa.String(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('_password_hash')

    # ### end Alembic commands ###
